apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ge-postgres.fullname" . }}
  labels:
    {{- include "ge-postgres.labels" . | nindent 4 }} 
data:
  cmd_db_creator.sh: |
    #!/bin/sh
    # CREATE EXTENSION vector; has to be installed on os level
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
      CREATE USER $CUSTOM_POSTGRES_USER WITH PASSWORD '$CUSTOM_POSTGRES_PASSWORD';
      CREATE DATABASE $CUSTOM_POSTGRES_DB;
      ALTER USER $CUSTOM_POSTGRES_USER CREATEDB LOGIN;
      ALTER DATABASE $CUSTOM_POSTGRES_DB OWNER TO $CUSTOM_POSTGRES_USER;
      GRANT ALL ON SCHEMA public TO $CUSTOM_POSTGRES_USER;
      GRANT CREATE ON DATABASE $CUSTOM_POSTGRES_DB TO $CUSTOM_POSTGRES_USER;
      GRANT ALL PRIVILEGES ON DATABASE $CUSTOM_POSTGRES_DB TO $CUSTOM_POSTGRES_USER;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $CUSTOM_POSTGRES_USER;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $CUSTOM_POSTGRES_USER;
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $CUSTOM_POSTGRES_USER;
    EOSQL
  entrypoint.sh: |
    #!/bin/sh
    # CREATE EXTENSION vector; has to be installed on os level
    echo "### GITEA DB CREATING"
    CUSTOM_POSTGRES_USER=$GITEA_POSTGRES_USER
    CUSTOM_POSTGRES_DB=$GITEA_POSTGRES_DB
    CUSTOM_POSTGRES_PASSWORD=$GITEA_POSTGRES_PASSWORD
    . /app/cmd_db_creator.sh
    echo "### BACKEND DB CREATING"
    CUSTOM_POSTGRES_USER=$BACKEND_POSTGRES_USER
    CUSTOM_POSTGRES_DB=$BACKEND_POSTGRES_DB
    CUSTOM_POSTGRES_PASSWORD=$BACKEND_POSTGRES_PASSWORD
    . /app/cmd_db_creator.sh
    echo "### WEBSOCKET DB CREATING"
    CUSTOM_POSTGRES_USER=$WEBSOCKET_POSTGRES_USER
    CUSTOM_POSTGRES_DB=$WEBSOCKET_POSTGRES_DB
    CUSTOM_POSTGRES_PASSWORD=$WEBSOCKET_POSTGRES_PASSWORD
    . /app/cmd_db_creator.sh
    POSTGRES_PASSWORD: admin1234
  
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: ge-postgres.{{ .Release.Namespace }}.svc.cluster.local
  POSTGRES_PORT: 5432
  PGDATA: /var/lib/postgresql/data
  GITEA_POSTGRES_USER: gitea
  GITEA_POSTGRES_DB: gitea
  GITEA_POSTGRES_PASSWORD: admin1234
  FROST_POSTGRES_USER: sensorthings
  FROST_POSTGRES_DB: sensorthings
  FROST_POSTGRES_PASSWORD: admin1234
  BACKEND_POSTGRES_USER: admin
  BACKEND_POSTGRES_DB: backend
  BACKEND_POSTGRES_PASSWORD: admin1234
  WEBSOCKET_POSTGRES_USER: admin
  WEBSOCKET_POSTGRES_DB: websocket
  WEBSOCKET_POSTGRES_PASSWORD: admin1234