apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ge-postgres.fullname" . }}
  labels:
    {{- include "ge-postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: admin1234
  # POSTGRES_HOST: ge-postgres.{{ .Release.Namespace }}.svc.cluster.local
  # POSTGRES_PORT: 5432
  # PGDATA: /var/lib/postgresql/data
  # GITEA_POSTGRES_USER: gitea
  # GITEA_POSTGRES_DB: gitea
  # GITEA_POSTGRES_PASSWORD: admin1234
  # FROST_POSTGRES_USER: sensorthings
  # FROST_POSTGRES_DB: sensorthings
  # FROST_POSTGRES_PASSWORD: admin1234
  # BACKEND_POSTGRES_USER: admin
  # BACKEND_POSTGRES_DB: backend
  # BACKEND_POSTGRES_PASSWORD: admin1234
  # WEBSOCKET_POSTGRES_USER: admin
  # WEBSOCKET_POSTGRES_DB: websocket
  # WEBSOCKET_POSTGRES_PASSWORD: admin1234