apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
  name: {{ include "ge-postgres.fullname" . }}
  labels:
    {{- include "ge-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ge-postgres.selectorLabels" . | nindent 4 }}
