apiVersion: v1
kind: Service
metadata:
  name: {{ include "ge-postgres.fullname" . }}
  labels:
    {{- include "ge-postgres.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- if .Values.service.annotations.metallbLoadBalancer.pool }}
    metallb.universe.tf/address-pool: {{ .Values.service.annotations.metallbLoadBalancer.pool }}
    {{- end }}
    {{- if .Values.service.annotations.metallbLoadBalancer.ip }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.service.annotations.metallbLoadBalancer.ip }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ge-postgres.selectorLabels" . | nindent 4 }}
