apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-http
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    {{- if .Values.service.http.labels }}
    {{- toYaml .Values.service.http.labels  | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.http.metallb }}
    metallb.universe.tf/address-pool: "configmap-public-ips"
    metallb.universe.tf/loadBalancerIPs: "{{ .Values.service.http.metallb.ip }}"
    {{- end }}
    {{- if .Values.service.http.annotations }}
    {{- toYaml .Values.service.http.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.http.type }}
  {{- if eq .Values.service.http.type "LoadBalancer" }}
  {{- if .Values.service.http.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.http.loadBalancerClass }}
  {{- end }}
  {{- if and .Values.service.http.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.http.loadBalancerIP  }}
  {{- end }}
  {{- if .Values.service.http.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.http.loadBalancerSourceRanges }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.http.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.http.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.http.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.http.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.http.ipFamilies }}
  ipFamilies:
  {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- if .Values.service.http.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.http.externalTrafficPolicy }}
  {{- end }}
  {{- if and .Values.service.http.clusterIP (eq .Values.service.http.type "ClusterIP") }}
  clusterIP: {{ .Values.service.http.clusterIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    {{- if  .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
    targetPort: {{ .Values.gitea.config.server.HTTP_PORT }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
